# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aeef7c2ed96a63e66e4c8806dc8cda63241d75d61a814668729d8ded4288f9068d8426ee5d238ed39fbb37f0e21ba493ec9fc5119e2503569e01d6d59cf155c

test:
  secret_key_base: e9934b3bf5b84e5373311f0a26c711d1dda823791df7d08f6170076ddb032194a70bf3a5fc4d0734d2de88117b83fe4fec77d8518993560a69f444f3cc326988

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
